- name: tap extra repositories
  homebrew_tap:
    tap: sanemat/font
    state: present
  tags: homebrew-tap

- name: install Recty font
  homebrew:
    name: ricty
    state: present
    install_options: with-powerline
  tags: recty-install

- name: depoy font file
  shell: cp -f /usr/local/opt/ricty/share/fonts/Ricty*.ttf ~/Library/Fonts/

- name: refresh font file cache
  shell: fc-cache -vf